# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea0d782099cd817ba37062b8681e32f5d9b40905ece790ec77f496f85a04dc11ec0859e49e0e2eeb195587983ac8e2eb1e8df8ac4f8092c1365d3328d70b9e41

test:
  secret_key_base: 32d89194b98e730f3b5bafa9dec726afa4e43cf8ec0eb6a781d0b285766af439f0900c891eedbba3cdfb1dfbcd49906f6d6fa6651373d913037c70249f226b97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
